version: '3.8'

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wp_files:
  db_data:

networks:
  inception:

