version: "3"

services:
  nginx:
    build: ./srcs/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - mynetwork
    restart: always

  wordpress:
    build: ./srcs/wordpress
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    restart: always

  mariadb:
    build: ./srcs/mariadb
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
